In [2]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:

df = pd.read_csv('train.txt',sep = ';',header = None,names = ['text','emotion'])

In [ ]:

df.isnull().sum()

text       0
emotion    0
dtype: int64

In [ ]:

unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i = 0
for emo in unique_emotions:
  emotion_numbers[emo] = i
  i +=1

df['emotion'] = df['emotion'].map(emotion_numbers)

In [ ]:
df

                                                   text  emotion
0     im feeling rather rotten so im not very ambiti...        0
1             im updating my blog because i feel shitty        0
2     i never make her separate from me because i do...        0
3     i left with my bouquet of red and yellow tulip...        1
4       i was feeling a little vain when i did this one        0
...                                                 ...      ...
1995  i just keep feeling like someone is being unki...        3
1996  im feeling a little cranky negative after this...        3
1997  i feel that i am useful to my people and that ...        1
1998  im feeling more comfortable with derby i feel ...        1
1999  i feel all weird when i have to meet w people ...        2

[2000 rows x 2 columns]

In [ ]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [ ]:

import string

def remove_punc(txt):
  return txt.translate(str.maketrans('','',string.punctuation))

In [ ]:
df['text'] = df['text'].apply(remove_punc)

In [ ]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [ ]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [ ]:
import nltk

In [ ]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [ ]:
stop_words = set(stopwords.words('english'))
print(stop_words)

{"i'm", 'will', 'ourselves', 'against', 'to', 'can', 'in', 'should', 'was', 'o', 'didn', 'on', 'my', 'themselves', "they'll", "we'd", 'had', 'over', 'the', 't', 'by', 'what', 'won', 'before', 'be', "i'd", 'up', 'do', 'why', 'yours', "couldn't", "mustn't", 'further', 'm', 'at', 'again', 'itself', 'y', "you'd", "don't", 'out', 'after', 'once', 'its', 'you', 'have', 'did', 'we', 'd', "we've", 'shan', 'his', 'having', 'haven', 'from', 'shouldn', 'me', "haven't", 'about', 'into', "didn't", 'between', "he's", 'how', "it'll", 'some', 'is', 'of', 'them', "they'd", 'mightn', 'yourself', 'own', 'only', 'where', 'her', "aren't", 'myself', "we're", 'are', 'a', 'who', 'has', 'when', 'other', 'this', "hadn't", 'himself', 'there', 'as', 'more', 'than', 'am', 'ours', 'just', 'same', 'hers', "he'll", "it'd", 've', 'most', 'because', 'needn', "i'll", "we'll", 'until', "wouldn't", 'isn', 'our', 'your', 'don', "mightn't", 'few', "they're", 'very', "won't", "she'll", 'off', 'both', 'these', 'were', 'it', 'been', "hasn't", 'hasn', "needn't", "isn't", 'during', "wasn't", "you're", 'doing', "that'll", 'with', "it's", 'wouldn', 'if', 'herself', 'she', 'couldn', 'he', 'not', 'that', 'which', 'and', 'they', 'through', 'too', 'yourselves', 'being', "shouldn't", 'hadn', "should've", 'each', 'an', 'i', 'while', 'their', "he'd", "i've", 'ma', 's', 'those', 'weren', 'for', 'doesn', 'mustn', "you'll", 'then', 'under', 'above', 'here', 'or', "she's", "weren't", 'down', 'but', 'does', 'so', 'whom', "she'd", "you've", 'him', "shan't", 'no', "they've", 'theirs', 'ain', 'below', 'nor', 'all', 'aren', 'wasn', 'any', 'll', 're', "doesn't", 'such', 'now'}

In [ ]:
df.loc[1]['text']

'im updating my blog because i feel shitty'

In [ ]:
def remove(txt):
  word=word_tokenize(txt)
  clean=[]
  for i in word:
    if i not in stop_words:
      clean.append(i)
  return ' '.join(clean)

In [ ]:
nltk.download('punkt_tab')
df['text'] = df['text'].apply(remove)

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

In [ ]:
df.loc[1]['text']

'im updating blog feel shitty'

In [5]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.20, random_state=42)

In [6]:
#CountVector is used for bag of word
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

#Multinomial is used for classification task where the feature and input data is discrete
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)


nb_model = MultinomialNB()
nb_model.fit(X_train_bow, y_train)


pred_bow = nb_model.predict(X_test_bow)
print(accuracy_score(y_test, pred_bow))

0.5875

In [7]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)


nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [8]:
y_pred = nb2_model.predict(X_test_tfidf)

print(accuracy_score(y_test, y_pred))

0.5175